<?php

namespace Webit\CMSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FaqCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqCategoryRepository extends EntityRepository
{
    /**
     * getting active category objects in specified language
     * @param string $lang
     * @return array
     */
    public function getActiveCategories($lang = 'en')
    {
        $qb = $this->createQueryBuilder('cat')                
                ->innerJoin('cat.Translations', 'trans')
                ->select('cat')
                ->addSelect('trans')
                ->where('trans.lang = :lang')
                ->andWhere('cat.isActive = :active')
                ->orderBy('cat.weight', 'asc')

                ->setParameter('lang', $lang)
                ->setParameter('active', true)
                ;
        $query = $qb->getQuery();

        return $query->getArrayResult();
    }
}
