<?php

namespace Webit\CMSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FaqQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqQuestionRepository extends EntityRepository
{
    public function getActiveQuestions($lang = 'en', $category_id = null)
    {
        $qb = $this->createQueryBuilder('q')
                ->innerJoin('q.Translations', 'trans')
                ->select('q', 'trans')
                ->where('trans.lang = :lang')
                ->andWhere('q.isActive = :active')
                ->orderBy('q.weight', 'asc')
                ->setParameter('lang', $lang)
                ->setParameter('active', true);

        if ($category_id) {
            $qb->andWhere('q.categoryId = :cat')
                    ->setParameter('cat', $category_id);
        }

        $query = $qb->getQuery();

        return $query->getResult();
    }

}
