<?php

namespace Webit\CMSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MenuItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuItemRepository extends EntityRepository
{
    public function getItemsByMenuId($lang = 'en', $parent_id = null)
    {        
        $q_builder = $this->createQueryBuilder('m')
                            ->select('m, m.id as item_id, m.route, m.link, m.isTargetBlank, m.contentId, '
                                    . 't.parentId, t.displayLabel, '
                        . 'c.id as content_id, c.slug as content_slug, '
                        . 'children.id as childs')
                        //    ->where('m.menuId = :menu_id')
                ->andWhere('m.isActive = :active')
                ->innerJoin('m.Translations', 't')
                ->andWhere('t.lang = :lang')
                ->leftJoin('m.content', 'c')
                ->addOrderBy('m.weight', 'asc')
                ->leftJoin('m.ChildrenItems', 'children')
                ->setParameter(':lang', $lang)
                         //   ->setParameter(':menu_id', $menu_id)
                ->setParameter(':active', true)
               ->groupBy('m.id')
        ;
        if(is_null($parent_id)){
            $q_builder->andWhere('m.parentMenuItemId is null');
        }else{
            $q_builder->andWhere('m.parentMenuItemId = :parent_id')
                      ->setParameter(':parent_id', $parent_id);
        }

        $query = $q_builder->getQuery();
        $objs = $query->getArrayResult();
    
        return $objs;
    }
}
