<?php

namespace Webit\CMSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends EntityRepository
{

        public function getSliderImages($lang='en')
        {
            $q = $this->createQueryBuilder('s')
                    ->select('s.image,s.route,s.title,s.description,s.description2,c.slug,c.id as page_id')
                    ->leftJoin('s.content', 'c') 
                    ->Where('s.lang = :lang')
                    ->andWhere('s.active=:active')
                    ->setParameter('lang', $lang)
                    ->setParameter('active', 1)
                    ->addOrderBy('s.weight', 'desc')
                    ->getQuery();

            return $q->execute();
        }
}
