<?php

namespace Webit\UserLogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LoginLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginLogRepository extends EntityRepository
{
    /**
     * 
     * @param \Application\Sonata\UserBundle\Entity\User $fos_usr
     * @param string $module     
     * @param string $ip
     * @return \Webit\UserLogBundle\Entity\BatchActivityLog
     */
    public function createLog( $fos_usr, $ip=null)
    {
        $login_log = new LoginLog();

        $login_log->setFosUser($fos_usr);    
        $login_log->setIpAddress($ip);                        
        $login_log->setTime(new \DateTime());

        $em = $this->getEntityManager();
        $em->persist($login_log);
        $em->flush();

        return $login_log;
    }
}
