<?php

namespace Webit\UserLogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Webit\UserLogBundle\Entity\UserLog;

/**
 * UserLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLogRepository extends EntityRepository
{
    /**
     * creating new log object
     * @param PortalUser $logged_user
     * @param string $subject
     * @param string $body
     * @return UserLog
     */
    public function createLog($logged_user,  $subject, $fos_usr = null, $body=null)
    {
        $user_log = new UserLog();

        $user_log->setLoggedUser($logged_user);
        //$user_log->setModifierUser($modifier_user);
        $user_log->setSubject($subject);
        $user_log->setBody($body);
        if($fos_usr instanceOf \Webit\ForexCoreBundle\Entity\PortalUser){
            $fos_usr = null;
        }
        $user_log->setFosUser($fos_usr);
        $user_log->setCreatedAt(new \DateTime());

        $em = $this->getEntityManager();
        $em->persist($user_log);
        $em->flush();

        return $user_log;
    }
    
    /**
     * get latest logs created in the system
     * @param int $limit
     * @return array
     */
    public function getLatestLogs($limit = 5){
        $qb = $this->createQueryBuilder('l')
                ->addOrderBy('l.createdAt', 'desc')
                ->setMaxResults($limit);
        return $qb->getQuery()->execute();
    }
}
