<?php

namespace Webit\ForexCoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Webit\ForexCoreBundle\Entity\CodeTradingGroup;

/**
 * CallbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeTradingGroupRepository extends EntityRepository
{
    /**
     * get or create group
     * @param string $name
     * @return CodeTradingGroup
     */
    public function getOrCreateByName($name) {
        $group = $this->findOneBy(array('name'=>$name));

        if(!$group){
            $group = new CodeTradingGroup();
            $group->setName($name);

            $this->_em->persist($group);
            $this->_em->flush();
        }

        return $group;
    }        
}
