<?php

namespace Webit\ForexCoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DemoProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemoProfileRepository extends EntityRepository
{
}
