<?php

namespace Webit\ForexCoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Webit\ForexCoreBundle\Entity\DocumentsTranslation;
use Webit\ForexCoreBundle\Entity\PortalUser;

/**
 * DocumentsTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentsTranslationRepository extends EntityRepository
{
    /**
     * getting translation object by user
     * @param PortalUser $portal_user
     * @param smallint $document_type
     * @return DocumentTranslation
     */
    public function getTranslationByType(PortalUser $portal_user, $document_type){
        $qb = $this->createQueryBuilder('d')
                ->andWhere('d.userId = :user_id')
                ->andWhere('d.documentType = :doc_type')
                ->setParameter(':user_id', $portal_user->getId())
                ->setParameter(':doc_type', $document_type)
                ;
        
        return $qb->getQuery()->getOneOrNullResult();        
    }
    
    /**
     * get or create new translation document object by user and document type
     * @param PortalUser $portal_user
     * @param smallint $document_type
     * @return DocumentsTranslation
     */
    public function getOrCreateObject(PortalUser $portal_user, $document_type){
        $obj = $this->getTranslationByType($portal_user, $document_type);
        
        if($obj === null){
            $obj = new DocumentsTranslation();
            $obj->setPortalUser($portal_user);
            $obj->setDocumentType($document_type);
        }
        
        return $obj;
    }
}
