<?php

namespace Webit\ForexCoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PartnershipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnershipRepository extends EntityRepository
{

}
